import 'package:flutter/material.dart';

/// Build-time configuration.
///
/// Override at launch, e.g.:
/// ```
/// flutter run --dart-define=AIDRA_USE_REMOTE=true \
///             --dart-define=AIDRA_API_BASE_URL=https://api.aidra.app/v1
/// ```
abstract final class AppConfig {
  static const String appName = 'AIDRA';
  static const String tagline = "Connecting Help Before It's Too Late.";
  static const String version = '1.0.0';

  /// REST base URL — mirrors the API contract in `docs/PRD.md` §8.
  static const String apiBaseUrl = String.fromEnvironment(
    'AIDRA_API_BASE_URL',
    defaultValue: 'https://api.aidra.app/v1',
  );

  /// When false the app runs fully against the bundled demo dataset, which
  /// makes it runnable with no backend (hackathon/demo mode) while every
  /// repository keeps its real HTTP code path.
  static const bool useRemoteBackend = bool.fromEnvironment(
    'AIDRA_USE_REMOTE',
    defaultValue: false,
  );

  /// Firebase Authentication (STEP 4). When true, `main()` boots Firebase and
  /// the auth repository uses the real email / phone-OTP / Google flows.
  ///
  /// ```
  /// flutter run --dart-define=AIDRA_USE_FIREBASE=true
  /// ```
  ///
  /// Requires `lib/firebase_options.dart` (generated by `flutterfire
  /// configure`) or the `AIDRA_FIREBASE_*` defines below.
  static const bool useFirebase = bool.fromEnvironment(
    'AIDRA_USE_FIREBASE',
    defaultValue: false,
  );

  // ------------------------------------------------------- Firebase options
  // Used by the generated-file placeholder in `lib/firebase_options.dart`.
  // `flutterfire configure` replaces that file with real per-platform values.
  static const String firebaseApiKey =
      String.fromEnvironment('AIDRA_FIREBASE_API_KEY');
  static const String firebaseProjectId =
      String.fromEnvironment('AIDRA_FIREBASE_PROJECT_ID');
  static const String firebaseAppIdAndroid =
      String.fromEnvironment('AIDRA_FIREBASE_APP_ID_ANDROID');
  static const String firebaseAppIdIos =
      String.fromEnvironment('AIDRA_FIREBASE_APP_ID_IOS');
  static const String firebaseAppIdWeb =
      String.fromEnvironment('AIDRA_FIREBASE_APP_ID_WEB');
  static const String firebaseMessagingSenderId =
      String.fromEnvironment('AIDRA_FIREBASE_SENDER_ID');
  static const String firebaseAuthDomain =
      String.fromEnvironment('AIDRA_FIREBASE_AUTH_DOMAIN');
  static const String firebaseStorageBucket =
      String.fromEnvironment('AIDRA_FIREBASE_STORAGE_BUCKET');

  /// Google Maps SDK API Key (Android, iOS, Web).
  static const String googleMapsApiKey =
      String.fromEnvironment('AIDRA_GOOGLE_MAPS_API_KEY');

  static bool get hasGoogleMapsKey => googleMapsApiKey.isNotEmpty;

  /// OAuth *server* client ID (the Web client ID from Google Cloud Console).
  /// Required on Android to receive an `idToken` from Google Sign-In.
  static const String googleServerClientId =
      String.fromEnvironment('AIDRA_GOOGLE_SERVER_CLIENT_ID');

  static const Duration apiTimeout = Duration(seconds: 20);

  // -------------------------------------------------------- session policy
  /// Local session lifetime when the AIDRA backend is unavailable and the
  /// Firebase ID token is used directly as the bearer token.
  static const Duration localSessionTtl = Duration(hours: 12);

  /// Refresh the access token this long before it expires, so a request never
  /// leaves the device with a token that dies mid-flight.
  static const Duration refreshSkew = Duration(minutes: 5);

  /// Auto-logout after this long with no user interaction (NFR: unattended
  /// devices in shelters and command centres must not stay logged in).
  static const Duration idleTimeout = Duration(minutes: 30);

  /// How often the session watchdog re-checks expiry + idleness.
  static const Duration sessionWatchInterval = Duration(seconds: 30);

  /// Upper bound on OTP resend requests per phone number per session.
  static const int maxOtpResends = 3;

  /// Length of the SMS code Firebase sends.
  static const int otpLength = 6;
  static const Duration syncInterval = Duration(seconds: 30);
  static const Duration refreshInterval = Duration(seconds: 45);

  /// Default map centre (Hyderabad) until GPS locks.
  static const double defaultLatitude = 17.3850;
  static const double defaultLongitude = 78.4867;
  static const double defaultZoom = 12.5;

  /// Languages shipping in v1 (PRD FR-901).
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('hi'),
    Locale('te'),
    Locale('ta'),
    Locale('es'),
  ];

  static const List<String> supportedLanguageNames = <String>[
    'English',
    'हिन्दी (Hindi)',
    'తెలుగు (Telugu)',
    'தமிழ் (Tamil)',
    'Español (Spanish)',
  ];

  /// Accessibility defaults (NFR: WCAG 2.1 AA).
  static const double minTapTarget = 48;
  static const bool defaultBoldText = false;

  /// Offline behaviour.
  static const int maxOutboxAttempts = 5;
  static const int maxCachedReports = 200;
}
